### PR TITLE
Add smile support to clj-json

### PR DESCRIPTION
**Pull request by dakrone**
Hi mmcgrana,
I forked clj-json to add SMILE support, since it was added to Jackson in 1.6.0.

Feel free to discard the project.clj description/url/name changes, we needed a version of clj-json to use at work that was on clojars, so I pushed a SNAPSHOT version for our leiningen projects.

### CODE REVIEW

**Comment by mmcgrana** [comment]
Hi Lee,

Do you have any benchmark results indicating the performance benefit that SMILE gets you with clj-json? I'm not saying that is a sufficient condition to have this merged, I'm just curious.
- Mark

**Comment by dakrone** [comment]
Hi Mark,

I don't have any benchmark numbers for _just_ SMILE on hand, but I can point you here: http://www.cowtowncoder.com/blog/archives/2010/09/entry_418.html

In section 2.4: "Smile is typically 25-50% faster and produces 25-50% more compact data than Jackson with textual JSON."

Hopefully this helps, let me know if there's anything else I can do.

**Comment by mmcgrana** [comment]
Maybe adapt this?

https://gist.github.com/316675

I'd be curious to see the results for new Clojure and JSON lib versions, as well as with SMILE.

**Comment by dakrone** [comment]
```
user=> (use 'jsontest.core)
nil
user=> (testit)            
Clojure version:  1.2.0
Num roundtrips:   100000

Trail:  1
clj-json                               2.15
clj-json-smile                         3.88
clj-json w/ keywords                   2.66
clj-serializer                         2.41
clojure printer/reader                 6.95
clojure printer/reader w/ print-dup    12.73
org.danlarkin.json                     21.35
clojure.contrib.json                   13.01

Trail:  2
clj-json                               1.30
clj-json-smile                         2.57
clj-json w/ keywords                   2.36
clj-serializer                         1.69
clojure printer/reader                 5.98
clojure printer/reader w/ print-dup    12.42
org.danlarkin.json                     21.05
clojure.contrib.json                   12.51

Size comparison:
clj-json        223
clj-json-smile  178
```

**Comment by dakrone** [comment]
Not sure what to make of that, SMILE may come out ahead in larger tests since binary compression would be more apparent (then again, it may not).

**Comment by dakrone** [comment]
Hi Mark,
Any word on whether you're okay with pulling this? Haven't heard from you in a while.

**Comment by mmcgrana** [comment]
Why again do you want this performance-oriented feature that apparently is not particularly performant? I don't plan on pulling this unless these is a strong reason for adding SMILE support.

**Comment by dakrone** [comment]
We use SMILE to talk to Elasticsearch, which Shay (the developer of ES) has told us ES can index faster, with less bytes sent over the wire. Jackson is the only library that supports SMILE at the moment, so rather than creating a separate Jackson-SMILE library, I added the feature to the existing clj-json library.

If you don't think it's a good idea to have in the library, I will pull it off into it's own. I was just attempting to avoid duplicating the Jackson-specific code.

**Comment by cowtowncoder** [comment]
Not sure if this helps, but the most commonly referred existing public benchmark -- https://github.com/eishay/jvm-serializers/wiki -- does show measurable improvements. There isn't tons of configurability that affects performance; but one thing that determines balance between compressibility and performance is that of whether to look for back-references for repeated property names and string values. Disabling both (or at least latter) help serialization speed; especially if there is no repetition, and enabling can help reduce size (and deserialization speed). By default only property name back-ref checks are enabled, and string value checks disabled.
Finally, there is now need google group for smile discussion (http://groups.google.com/group/smile-format-discussion), where feedback on observed differences would be most welcome (in fact, cases where Smile does not help are very useful).

**Comment by dakrone** [comment]
Closing

**Pull request closed without merging**
