### PR TITLE
Java 6 compatibility

### PR DESCRIPTION
**Pull request by tedpennings**
Please consider adding Java 6 compatibility to clj-json. 

clj-json doesn't appear to have any Java 7 dependencies or requirements. Oracle still supports Java 6. It's always a good practice to support the current and previous release of Java.

This pull request adds javac flags to compile code for Java 6.

### CODE REVIEW

**Comment by dribnet** [comment]
:+1:

**Comment by charleslparker** [comment]
Yes, please do consider this.

**Comment by ghost** [comment]
+1 -- we can't use this library without 6 support

**Comment by finnjohnsen** [comment]
just use cheshire, this is probably abandoned

**Comment by charleslparker** [comment]
Easy reference for future excavators:

https://github.com/dakrone/cheshire

clojure/data.json is also nice if speed isn't a big concern.

https://github.com/clojure/data.json

**Comment by tedpennings** [comment]
This is abandoned.

**Pull request closed without merging**
